# Generated by Django 2.2.8 on 2020-02-17 15:45

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20191215_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(blank=True, classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock(blank=True)), ('embed', wagtail.embeds.blocks.EmbedBlock(blank=True)), ('image', wagtail.images.blocks.ImageChooserBlock(blank=True)), ('mapurl', wagtail.core.blocks.CharBlock('Google Map URL', blank=True, max_length=500, null=True)), ('calendarurl', wagtail.core.blocks.URLBlock('URL for calendar', blank=True, null=True)), ('buttonLink', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.TextBlock(blank=True)), ('link', wagtail.core.blocks.URLBlock(blank=True, label='external URL'))])), ('jumbotron', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock(blank=True, classname='full title')), ('classes', wagtail.core.blocks.CharBlock(blank=True, label='CSS classes from BS (text-light or text-dark)', required=False)), ('text', wagtail.core.blocks.TextBlock(blank=True, required=False)), ('buttonLabel', wagtail.core.blocks.CharBlock(blank=True, label='Text on button', required=False)), ('buttonUrl', wagtail.core.blocks.URLBlock(blank=True, required=False)), ('background', wagtail.images.blocks.ImageChooserBlock(blank=True, required=False))])), ('testimonial', wagtail.core.blocks.StructBlock([('test_name', wagtail.core.blocks.TextBlock(blank=True)), ('test_quote', wagtail.core.blocks.TextBlock(blank=True)), ('test_reversed', wagtail.core.blocks.BooleanBlock(default=False, required=False)), ('test_pic', wagtail.images.blocks.ImageChooserBlock(blank=True))])), ('carousel', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('title', wagtail.core.blocks.CharBlock('Title ...', blank=True, max_length=250)), ('caption', wagtail.core.blocks.TextBlock(blank=True, required=False)), ('button', wagtail.core.blocks.TextBlock(required=False)), ('link', wagtail.core.blocks.URLBlock(required=False))]), blank=True, icon='image', null=True))], blank=True, null=True),
        ),
    ]
