# Generated by Django 2.2.8 on 2020-02-17 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200217_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='buttonLabel',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='buttonUrl',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='heading',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='text',
        ),
        migrations.DeleteModel(
            name='Carousel',
        ),
    ]
