# Generated by Django 2.2.8 on 2020-02-18 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200217_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='google_ad_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
